service: auto-qpcr
runtime: python37
api_version: 1
threadsafe: true

handlers: 
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  upload: /.*\.(csv)$

libraries:
- name: ssl
  version: latest



