# runtime: python37
runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.conf.py --graceful-timeout 90 --timeout 90 -b :$PORT main:app
runtime_config:
  python_version: 3.6

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
